# Generated by Django 4.0.3 on 2022-05-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('provincia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=40)),
                ('carrera', models.CharField(max_length=40)),
                ('tiempoCursado', models.IntegerField()),
                ('egresado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
